language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install nose pylint pytest-json"
# command to run tests
script: "pylint *.py && py.test --json=report.json && cat report.json"
